wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/my_DQN.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.19
    start_time: 1721828769.387639
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.9.19
      5: 0.13.11
      8:
      - 5
batch_size:
  desc: null
  value: 128
buffer_size:
  desc: null
  value: 5000
capture_video:
  desc: null
  value: false
cuda:
  desc: null
  value: true
end_e:
  desc: null
  value: 0.0
env_id:
  desc: null
  value: Anki_Overdrive
exp_name:
  desc: null
  value: my_DQN
exploration_fraction:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.99
hf_entity:
  desc: null
  value: ''
learning_rate:
  desc: null
  value: 1.0e-05
learning_starts:
  desc: null
  value: 200
num_envs:
  desc: null
  value: 1
save_model:
  desc: null
  value: true
seed:
  desc: null
  value: 1
start_e:
  desc: null
  value: 1
target_network_frequency:
  desc: null
  value: 32
tau:
  desc: null
  value: 1.0
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 3000
track:
  desc: null
  value: true
train_frequency:
  desc: null
  value: 7
upload_model:
  desc: null
  value: false
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: cleanRL_classicalRL
